# Generated by Django 4.0.3 on 2022-05-09 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0012_remove_hotel_type_archive'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Archive',
        ),
    ]
