# Generated by Django 4.0.3 on 2022-05-10 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0014_archive'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserArchive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0)),
                ('password', models.CharField(default=None, max_length=64)),
                ('username', models.CharField(default=None, max_length=64)),
                ('first_name', models.CharField(default=None, max_length=64)),
                ('last_name', models.CharField(default=None, max_length=64)),
                ('phone', models.CharField(default=None, max_length=64)),
            ],
        ),
    ]
