# Generated by Django 4.0.3 on 2022-05-10 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0015_userarchive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userarchive',
            name='password',
            field=models.CharField(default=None, max_length=250),
        ),
    ]
