# Generated by Django 4.0.3 on 2022-05-11 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0016_alter_userarchive_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userarchive',
            name='password',
        ),
        migrations.AlterField(
            model_name='hotel',
            name='overview',
            field=models.CharField(default=None, max_length=500),
        ),
    ]
