# Generated by Django 4.0.3 on 2022-05-11 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0017_remove_userarchive_password_alter_hotel_overview'),
    ]

    operations = [
        migrations.AddField(
            model_name='archive',
            name='password',
            field=models.CharField(default=None, max_length=64),
        ),
    ]
