# Generated by Django 4.0.3 on 2022-05-11 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0018_archive_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archive',
            name='password',
        ),
        migrations.AddField(
            model_name='category',
            name='room_type',
            field=models.CharField(default=None, max_length=64),
        ),
    ]
