# Generated by Django 4.0.3 on 2022-05-11 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0019_remove_archive_password_category_room_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='room_type',
        ),
    ]
