# Generated by Django 4.0.3 on 2022-05-11 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0020_remove_category_room_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='room_type',
            field=models.CharField(default=None, max_length=64),
        ),
    ]
